name: 部署图片到 R2

on:
  workflow_dispatch:

jobs:
  sync_to_r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 同步图片到 R2
        uses: DullJZ/sync-r2-action@v1
        with:
          # 使用 Secrets 传递凭证
          r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2_endpoint: ${{ secrets.R2_ENDPOINT }} # 也将你的 R2 endpoint 作为 Secret 存储
          r2_bucket_name: ${{ secrets.R2_BUCKET_NAME }}
